MyDog/MyDog/Models/Cani.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyDog.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cani
    {
        public int Id { get; set; }
        public string Nome { get; set; }
        public string Descrizione { get; set; }
        public int IdCategoria { get; set; }
    
        public virtual Categorie Categorie { get; set; }
    }
}

MyDog/MyDog/Controllers/CaniController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MyDog.Models;

namespace MyDog.Controllers
{
    public class CaniController : Controller
    {
        // GET: Cani
        public ActionResult Index()
        {
            List<Cani> model = new List<Cani>();
            using (DOG_DBEntities db = new DOG_DBEntities())
            {
                model = db.Cani.ToList();
            }
            //return dogs list
            return View(model);
        }

        // GET: Cani/Details/5
        //public ActionResult Details(int id)
        //{
        //    return View();
        //}

        //GET: Cani/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Cani/Create
        [HttpPost]
        public ActionResult Create(Cani cane)
        {
            try
            {
                cane.IdCategoria = 1;
                using (DOG_DBEntities db = new DOG_DBEntities())
                {
                    db.Cani.Add(cane);
                    db.SaveChanges();
                }


                return RedirectToAction("Index");
            }
            catch(Exception ex)
            {
                return View();
            }
        }

        // GET: Cani/Edit/5
        //public ActionResult Edit(int id)
        //{
        //    return View();
        //}

        // POST: Cani/Edit/5
        //[HttpPost]
        //public ActionResult Edit(int id, FormCollection collection)
        //{
        //    try
        //    {
        //        // TODO: Add update logic here

        //        return RedirectToAction("Index");
        //    }
        //    catch
        //    {
        //        return View();
        //    }
        //}

        // GET: Cani/Delete/5
        //public ActionResult Delete(int id)
        //{
        //    return View();
        //}

        // POST: Cani/Delete/5
        //[HttpPost]
        //public ActionResult Delete(int id, FormCollection collection)
        //{
        //    try
        //    {
        //        // TODO: Add delete logic here

        //        return RedirectToAction("Index");
        //    }
        //    catch
        //    {
        //        return View();
        //    }
        //}
    }
}

MyDog/MyDog/Controllers/CategorieController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MyDog.Models;

namespace MyDog.Controllers
{
    public class CategorieController : Controller
    {
        // GET: Categorie
        public ActionResult Index(int idCategoriaCane)
        {
            //ViewBag.idCategoriaCane = idCategoriaCane;
            Categorie categoria = new Categorie();
            DOG_DBEntities db = new DOG_DBEntities();

            // Query for all blogs with names starting with B 
            Categorie category = (from Categorie c in db.Categorie
                where c.Id.Equals(idCategoriaCane)
                select c).First();

            return View(category);
        }
    }
}

MyDog/MyDog/Views/Cani/Create.cshtml
@model MyDog.Models.Cani

@{
    ViewBag.Title = "Create";
}

<h2>Inserisci qui il tuo cane</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Cani</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Descrizione, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Descrizione, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Descrizione, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IdCategoria, "IdCategoria", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("IdCategoria", new List<SelectListItem>(), htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.IdCategoria, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Torna alla lista", "Index")
</div>

MyDog/MyDog/Views/Cani/Index.cshtml
@using MyDog.Models
@model List<MyDog.Models.Cani>

@{
    ViewBag.Title = "LISTA CANI IN ARCHIVIO";
}

<h2>Di seguito la lista cani aggiornata ad @DateTime.Now</h2>

<table>
    <tr>
        <td>NOME RAZZA</td>
        <td>DESCRIZIONE RAZZA</td>
        <td>CATEGORIA</td>
    </tr>
    @foreach (Cani cane in Model)
    {
        <tr>
            <td>@cane.Nome</td>
            <td>@cane.Descrizione</td>
            <td>@Html.ActionLink("Vai a categoria", "Index", "Categorie", new { idCategoriaCane = @cane.IdCategoria }, null )</td>
        </tr>
    }
</table>